---

train:
  agent: "MNISTAgent"
  device: "cuda"
  n_epochs: 10
  log_interval: 100
  log_dir: "run"
  exp_name: "mnist"
  mode: "vae"

dataset:
  root: "download"

dataloader:
  batch_size: 32
  num_workers: 4

model:
  latent_size: 2

optim:
  lr: 0.0001
