---

train:
  agent: "MNISTAgent"
  device: "cuda:1"
  n_epochs: 10
  log_interval: 100
  log_dir: "run"
  exp_name: "mnist_cvae"
  mode: "cvae"

dataset:
  root: "download"

dataloader:
  batch_size: 32
  num_workers: 4

model:
  latent_size: 32

optim:
  lr: 0.001
